### ISSUE TITLE
Allow selecting package manager that will be used/installed by autolibs on OSX

### ISSUE THREAD

**Issue by mpapis** [rvm/rvm#1627]
as we got support for few already we should allow users to specify which package manager would be used, to make it intuitive we could add few names for the numbers we have already:
- `0`: `disabled`
- `1`: `read(-only)`
- `2`: `(read-)fail` **(default)**
- `3`: `(install-)packages`
- `4`: `enabled`, `(home)brew`, `(mac)ports`, `fink`, `smf`, `upgrade`
# Tasks
- [x] Add flag names handling and change default to `2`
- [x] Add `rvm autolibs [enable|disable|status|...]` command
- [x] Improve `--autolibs=` support in installer
- [x] Migrate old autolibs settings from `/etc/rvmrc` / `~/.rvmrc` to `$rvm_path/user/db`
- [x] Migrate (remove) old SM Framework code from `/etc/rvmrc`
